### ISSUE TITLE
[Request] - Change the project name/title

### ISSUE THREAD

**Issue by lucasliet** [LeoGil/eco-coleta#2]
**Do you want to request a feature or report a bug?**
Feature(Maybe a bug?)

**What is the current behavior?**
Shitty name project

**What is the expected behavior?**
A Project name that makes any sense and doesn't sound like you're stuttering

**Please mention your node.js, yarn/npm and operating system version.**
- **node.js**: v12.18.0 
- **yarn**: v12.18.0 
- **OS**: Ubuntu 20.04

**Comment by LeoGil** [comment]
Sem tempo irmao kkkkkk
